#!/usr/bin/env node
// 安装 A股助手 preset 到 DSH（一键安装入口）。
//
// DSH 0.1.7+ 的预设机制（**与 0.1.5 完全不同**）：
//   预设不再是 ~/.dsh/.agent-presets/<id>/ 下的 yml 目录（registry 已明确"不扫描目录、
//   不接受预设路径"），而是 profile 组成里的一行 `@deepseek-ai/dsh-agent-preset`：
//       - id: preset-a-share-assistant
//         name: '@deepseek-ai/dsh-agent-preset'
//         config: { id, name, description, order, plugins: [ ...子插件行... ] }
//   自定义预设通过**用户层 patch** 插入：~/.dsh/profiles/<profile>/cordis.patch.yml
//   （`- insert: [ ... ]`；insert 里的相对插件路径以 patch 文件所在目录为基准）。
//   本脚本因此改为：把 presets/a-share-assistant/agent.cordis.yml 的子插件行包进
//   insert → 写进用户 patch（带标记注释，可重复安装/卸载），并把本地文件引用改成
//   绝对 file:// URL / 绝对路径（不再依赖 baseUrl）。
//
// 用法：
//   node scripts/install-preset.js [--profile web] [--uninstall] [--print]
//     --profile <name>  目标 profile（默认 web；即 `dsh web` 用的那个）
//     --print           只打印将写入的 patch 内容，不落盘
//     --uninstall       从用户 patch 中移除本预设（保留其它 patch 内容）
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

// ── 前置检查与平台探测 ───────────────────────────────────────────────────────
const nodeMajor = Number(process.version.slice(1).split('.')[0]);
if (nodeMajor < 18) {
  console.error(`✗ 需要 Node.js >= 18，当前 ${process.version}`);
  process.exit(1);
}
const PLATFORM = process.platform; // 'win32' | 'linux' | 'darwin' | ...
const PLATFORM_NOTE = PLATFORM === 'win32'
  ? '本机 PowerShell/curl 的 schannel TLS 不可用，取数一律走后端 node fetch，勿用 Invoke-WebRequest / curl'
  : '统一走后端 node fetch 取数最稳；Linux/macOS 下若要临时用 curl 亦可，但建议走 CLI';

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PRESET_ID = 'a-share-assistant';
const SRC_DIR = path.join(PROJECT_ROOT, 'presets', PRESET_ID);
const OLD_DEST_DIR = path.join(os.homedir(), '.dsh', '.agent-presets', PRESET_ID); // 0.1.5 的旧位置（已失效）

// ── 命令行参数 ──────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const opt = (name, def) => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : def;
};
const PROFILE = opt('profile', 'web');
const PRINT_ONLY = argv.includes('--print');
const UNINSTALL = argv.includes('--uninstall');
const DSH_HOME = process.env.DSH_HOME || path.join(os.homedir(), '.dsh');
const PATCH_FILE = path.join(DSH_HOME, 'profiles', PROFILE, 'cordis.patch.yml');

// 用户补丁块的起止标记（重装时整块替换，不动用户的其它 patch 内容）
const MARK_BEGIN = `# >>> ${PRESET_ID} (auto-generated by dsh-a-share-assistant; do not edit) >>>`;
const MARK_END = `# <<< ${PRESET_ID} <<<`;
// 系统产物根：{A_SHARE_HOME 或 cwd}/.a-share-assistant（与 src/config.js 的 homeDir 一致）
const USER_CFG = path.join(path.resolve(process.env.A_SHARE_HOME || process.cwd()), '.a-share-assistant', 'config.json');
const EXAMPLE_CFG = path.join(PROJECT_ROOT, 'config.example.json');

// ── 用户配置：只读；缺失时不自动生成（先问后建原则），TTY 下交互询问是否生成 ──
let config = null;
let configMissing = false;
if (fs.existsSync(USER_CFG)) {
  config = JSON.parse(fs.readFileSync(USER_CFG, 'utf8'));
} else {
  configMissing = true;
  config = {}; // 空配置：占位符回退到未配置状态
}

const CACHE_ROOT = String(config.cacheRoot || path.join(path.resolve(process.env.A_SHARE_HOME || process.cwd()), '.a-share-assistant', 'cache')).replace(/\//g, path.sep);
const NOTES_ROOT = (typeof (config.noteRoot ?? config.vaultRoot) === 'string' && (config.noteRoot ?? config.vaultRoot).trim())
  ? (config.noteRoot ?? config.vaultRoot)
  : null; // 未配置则不替换为路径，persona 中显示"未配置"

// 复盘目录：与 src/config.js 的 reviewDir() 同一套解析顺序
// （A_SHARE_REVIEW_DIR > config.reviewDir > 探测 {笔记库根}/学习/金融/复盘 > {cwd}/学习/金融/复盘 > {笔记库根}/复盘 > {cwd}/复盘）
const REVIEW_DIR = (() => {
  const fromEnv = process.env.A_SHARE_REVIEW_DIR;
  if (fromEnv && fromEnv.trim()) return path.resolve(fromEnv);
  const base = path.resolve(NOTES_ROOT || process.env.A_SHARE_HOME || process.cwd());
  const cfgDir = typeof config.reviewDir === 'string' && config.reviewDir.trim() ? config.reviewDir.trim() : null;
  if (cfgDir) return path.isAbsolute(cfgDir) ? cfgDir : path.join(base, cfgDir);
  const cands = [path.join(base, '学习', '金融', '复盘'), path.join(process.cwd(), '学习', '金融', '复盘'), path.join(base, '复盘')];
  for (const c of cands) { try { if (fs.statSync(c).isDirectory()) return c; } catch { /* 试下一个 */ } }
  return path.join(process.cwd(), '复盘');
})();

function replacer(text) {
  return text
    .replaceAll('__PROJECT_ROOT__', PROJECT_ROOT.split(path.sep).join('/'))
    .replaceAll('__CACHE_ROOT__', CACHE_ROOT.split(path.sep).join('/'))
    .replaceAll('__REVIEW_DIR__', REVIEW_DIR.split(path.sep).join('/'))
    .replaceAll('__NOTES_ROOT__', (NOTES_ROOT || '（未配置 noteRoot，工作目录提醒关闭）').split(path.sep).join('/'))
    .replaceAll('__PLATFORM_NOTE__', PLATFORM_NOTE)
    .replaceAll('__SKILL_MD__', path.join(SRC_DIR, 'skills', 'a-share-assistant', 'SKILL.md').split(path.sep).join('/'));
}

// ── 把 preset 的"子插件行列表"编译成 0.1.7 的 patch 插入块 ────────────────────
/**
 * 本地文件引用改成**字面**绝对路径（insert 的相对路径锚点不可控，显式更稳）。
 * 注意：`name` 字段在 0.1.7 的 schema 里只接受 string，**不能写 `!!js` 表达式**——
 * 声明在 registry 里被重新读取时表达式不会求值，会报
 * `row N names no plugin (a "name" string is required)`，导致该预设的会话无法 resume。
 * 因此这里直接写 `file://` URL 字符串（installer 装的时候路径已知）。
 */
function absoluteLocalPluginRefs(yaml) {
  const quarantineUrl = pathToFileURL(path.join(SRC_DIR, 'skill-quarantine.mjs')).href;
  const skillsDir = path.join(SRC_DIR, 'skills').split(path.sep).join('/');
  return yaml
    .replace(/^(\s*name:\s*)\.\/skill-quarantine\.mjs\s*$(.*)$/m, `$1'${quarantineUrl}'$2`)
    .replace(/^(\s*-\s*)!!js "process\.getBuiltinModule\('node:url'\)\.fileURLToPath\(new URL\('skills\/', baseUrl\)\)"\s*$/m, `$1'${skillsDir}'`);
}

/** 逐行缩进（保留空行与注释的相对结构） */
function indent(text, spaces) {
  const pad = ' '.repeat(spaces);
  return text.split('\n').map((l) => (l.trim() === '' ? l : pad + l)).join('\n');
}

function buildPatchBlock() {
  const meta = {};
  for (const line of fs.readFileSync(path.join(SRC_DIR, 'preset.yml'), 'utf8').split('\n')) {
    const m = /^([a-zA-Z]+):\s*(.*)$/.exec(line.trim());
    if (m) meta[m[1]] = m[2].trim();
  }
  const rows = absoluteLocalPluginRefs(replacer(fs.readFileSync(path.join(SRC_DIR, 'agent.cordis.yml'), 'utf8')));
  const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
  return [
    MARK_BEGIN,
    '- insert:',
    `    - id: preset-${PRESET_ID}`,
    "      name: '@deepseek-ai/dsh-agent-preset'",
    '      config:',
    `        id: ${PRESET_ID}`,
    `        name: ${q(meta.name || 'A股助手')}`,
    `        description: ${q(meta.description || '')}`,
    `        order: ${meta.order || 5}`,
    '        plugins:',
    indent(rows.trimEnd(), 10),
    MARK_END,
    '',
  ].join('\n');
}

/** 读取现有 patch，摘掉旧的自动生成块，返回 {head, body} */
function splitPatch(text) {
  const b = text.indexOf(MARK_BEGIN);
  const e = text.indexOf(MARK_END);
  if (b >= 0 && e > b) return { head: text.slice(0, b), body: text.slice(e + MARK_END.length) };
  return { head: '', body: text };
}

/** 用户其它内容是否为空（`[]` / 注释 / 空白 都算空） */
function isEmptyPatch(body) {
  return body.split('\n').every((l) => {
    const t = l.trim();
    return t === '' || t === '[]' || t.startsWith('#');
  });
}

function writePatch(block) {
  fs.mkdirSync(path.dirname(PATCH_FILE), { recursive: true });
  const existing = fs.existsSync(PATCH_FILE) ? fs.readFileSync(PATCH_FILE, 'utf8') : '[]\n';
  const { head, body } = splitPatch(existing);
  if (UNINSTALL) {
    const rest = isEmptyPatch(body) ? '[]\n' : body.replace(/^\s*\n/, '');
    fs.writeFileSync(PATCH_FILE, rest, 'utf8');
    return { existed: true, others: !isEmptyPatch(body) };
  }
  const others = isEmptyPatch(body) ? '' : body.replace(/^\s*\n/, '');
  const out = `${head}${block}${others && !others.trim().startsWith('[]') ? others : ''}`;
  fs.writeFileSync(PATCH_FILE, out, 'utf8');
  return { existed: true, others: Boolean(others) };
}

// 防御：绝不允许覆盖官方内置目录
if (PATCH_FILE.includes(path.join('@deepseek-ai', 'dsh', 'config'))) {
  console.error('拒绝安装：目标路径疑似官方内置目录');
  process.exit(1);
}

const block = buildPatchBlock();
if (PRINT_ONLY) {
  console.log(block);
  process.exit(0);
}
if (UNINSTALL) {
  const r = writePatch(block);
  console.log(`✔ 已从 ${PATCH_FILE} 移除「A股助手」预设${r.others ? '（保留了你的其它 patch 内容）' : ''}`);
  console.log('  重启/新开会话后生效；旧会话仍持有原组成直到重启。');
  process.exit(0);
}
if (!fs.existsSync(path.dirname(PATCH_FILE))) {
  console.error(`✗ 找不到 profile 目录: ${path.dirname(PATCH_FILE)}`);
  console.error('  确认 DSH 已装且该 profile 至少启动过一次（如 `dsh web`）；或用 --profile <name> 指定其它 profile。');
  process.exit(1);
}
const res = writePatch(block);
console.log(`✔ 已安装预设「A股助手」→ ${PATCH_FILE}`);
console.log(`  preset id: ${PRESET_ID}（DSH 0.1.7+ 的 profile patch 机制；旧版 .agent-presets 目录已不被扫描）`);
console.log(`  项目根: ${PROJECT_ROOT}`);
console.log(`  配置来源: ${USER_CFG}`);
console.log(`  缓存目录: ${CACHE_ROOT}`);
console.log(`  笔记库根: ${NOTES_ROOT}`);
console.log(`  复盘目录: ${REVIEW_DIR}（笔记与持仓分析报告都写这里；config.reviewDir 可覆盖）`);
console.log(`  平台: ${PLATFORM}（${PLATFORM_NOTE}）`);
if (res.others) console.log('  注意: 你的 cordis.patch.yml 里还有其它 patch 内容，本预设以标记块形式插入，未改动它们');
if (fs.existsSync(OLD_DEST_DIR)) {
  console.log('');
  console.log(`⚠️ 检测到 0.1.5 的旧安装位置仍在: ${OLD_DEST_DIR}`);
  console.log('   DSH 0.1.7 起 registry 不再扫描该目录（同样失效的还有 ~/.dsh/.agent-presets 下的其它预设，如「梁神模式」）。');
  console.log('   可以直接删除该目录；要保留请自行备份。');
}
console.log('');
console.log('支持矩阵：Windows（本机已验证）/ Linux、macOS（代码跨平台兼容，建议安装后先跑 `node src/cli.js check` 自检）');

// ── 配置缺失：交互引导生成（TTY），否则提示 ─────────────────────────────────
if (configMissing) {
  console.log('');
  console.log(`⚠️ 未检测到配置文件: ${USER_CFG}`);
  if (process.stdin.isTTY) {
    console.log('是否现在用 `cli.js config --init` 生成配置文件？（y=生成，编辑后填写 apiKey；n=稍后手动创建）');
    const { createInterface } = await import('node:readline/promises');
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    let answer = '';
    try { answer = (await rl.question('> ')).trim().toLowerCase(); } catch {}
    rl.close();
    if (answer === 'y' || answer === 'yes' || answer === '是') {
      console.log('→ 运行 config --init ...');
      spawnSync(process.execPath, [path.join(PROJECT_ROOT, 'src', 'cli.js'), 'config', '--init'], { stdio: 'inherit' });
      console.log('✔ 已生成配置，请编辑 `./.a-share-assistant/config.json`：');
      console.log('   必填 fuyao.apiKey（https://fuyao.aicubes.cn 签发）');
      console.log('   可选 iwencai.apiKey（https://www.iwencai.com/skillhub 获取，填了才有「公告/新闻」通道）');
    } else {
      console.log('→ 请稍后运行 `node src/cli.js config --init` 或 `config --template` 创建配置。');
    }
  } else {
    console.log('（非交互环境）运行 `node src/cli.js config --init`（生成）或 `--template`（模板）创建配置。');
  }
}

// ── 可选增强：问财「公告/新闻」通道（缺了不影响主链路）──────────────────────
const SKILLS_DIR = path.join(os.homedir(), '.agents', 'skills');
const IW_SKILLS = ['announcement-search', 'news-search'];
const installedIw = IW_SKILLS.filter((s) => fs.existsSync(path.join(SKILLS_DIR, s)));
if (installedIw.length < IW_SKILLS.length) {
  console.log('');
  console.log(`ℹ️ 可选增强（公告/新闻通道）：已装 ${installedIw.length}/${IW_SKILLS.length} 个问财技能`);
  console.log('   1) Key：把 iwencai.apiKey 写进 `.a-share-assistant/config.json`（https://www.iwencai.com/skillhub 获取）');
  console.log('   2) 技能：python <iwencai-skillhub-cli.py> --dir "%USERPROFILE%\\.agents\\skills" install announcement-search');
  console.log('            （news-search 同理；装完新开会话即可用 `node src/cli.js search --channel announcement|news --q "..."`）');
  console.log('   不装也完全可用：行情/财务/涨停龙虎榜/复盘/持仓分析走 fuyao，与这条通道无关。');
}

console.log('');
console.log('下一步：在 DSH Web 界面「新建会话」→ 预设选择「A股助手」，先跑 `node src/cli.js check` 自检。');
console.log('提示：当前已打开的会话不会热切换预设，需要新建会话生效。');

